baseURL = 'https://howtogetanabortion.in/'
languageCode = 'en-us'
title = 'How to get an abortion in the United States'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # also see "recent posts number" below
googleAnalytics = ""
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[languages]
  [languages.en]
    title = "How to get an abortion in the United States"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "mid-gray"
  author = ""
  favicon = "android-chrome-512x512.png"
  site_logo = ""
  description = "Information on abortion and reproductive health services in the United States."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-lightest-blue"
  # https://github.com/tachyons-css/tachyons/blob/v4.7.0/src/_font-family.css
  body_classes = "sans-serif bg-near-white"
  # https://themes.gohugo.io/themes/gohugo-theme-ananke/#custom-css
  custom_css = ["custom.css"]
  recent_posts_number = 10

[[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"